services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  backend:
    image: hr-sber-backend:latest
    build:
      context: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
      - kafka
